### ISSUE TITLE
Generate handy string-related helpers for graphql `Enum` types

### ISSUE THREAD

**Issue by develop7** [reasonml-community/graphql-ppx#134]
In order to avoid end users writing to&from `string` boilerplate helpers (which are essential when, for instance, populating a `<select>` with enum members) these should be generated by the ppx.

Given the following enum

```graphql
enum Foo {
	"Bar comment"
	Bar
	"Qux comment"
	Qux
}
```

we have following type generated

```reasonml
type foo = [ `Bar | `Qux ]
```

and in order to populate selects with the values of that type we need to have them converted to strings

```reasonml
let string_of_Foo = (foo: foo) => switch (foo ){
| `Bar => "Bar"
| `Qux => "Qux"
}
```

and other way around as well

```reasonml
let Foo_of_string = s => switch (s) {
| "Bar" => `Bar
| "Qux" => `Qux
}
```

I'd love to have these generated for me; or have [`@bs.deriving jsConverter`](https://bucklescript.github.io/docs/en/generate-converters-accessors.html#convert-between-js-string-enum-and-bs-polymorphic-variant) cast upon.

EDIT: removed irrelevant request

**Comment by jsiebern** [comment]
As discussed on Discord: I like the idea and we're gonna put this in.

Just a note on your last remark (comment function):
I believe this is too opinionated for an abstract ppx like this. Think the following cases:
- No comments (function yes / no? What would be the return value?)
- What about internationalized apps? If this would feature complete, it would need a special syntax of comments to maybe support that

Generally I believe this should be an implementation detail, esp. because most of the time these comments are used as developer information (inspecting the schema) rather than storing user facing values.

**Comment by develop7** [comment]
> Generally I believe this should be an implementation detail, esp. because most of the time these comments are used as developer information (inspecting the schema) rather than storing user facing values.

good point, that belongs to the l10n, it's just me trying to do a shortcut prototyping the app

**Comment by jfrolich** [comment]
Sorry for being lazy and not following up on this! It looks like this functionality is coming natively to BuckleScript, so I guess we don't need this anymore.
