### ISSUE TITLE
Template tags break fragments

### ISSUE THREAD

**Issue by jeddeloh** [reasonml-community/graphql-ppx#160]
It looks like using the template tags might break fragments.

```
// bsconfig.json
"ppx-flags": [
  [
    "-template-tag-import=gql",
    "-template-tag-location=@apollo/client"
  ]
],
```

Example query in Reason:
```
query Documents {
  documents(order_by: [{id: desc}]) {
    ...Fragments.Document
  }
}
```

Compiled JS with template tags:
```
var query = (require("@apollo/client").gql`
  query Documents  {
    documents(order_by: [{id: desc}])  {
      ...Document
    }
  }
`);
```
Without:
```
var query = "query Documents  {\ndocuments(order_by: [{id: desc}])  {\n..." + Fragments$AppName.Document.name + "   \n}\n\n}\n" + Fragments$AppName.Document.query;
```

**Comment by jfrolich** [comment]
Ah yes!! That was something I didn’t implement yet. Let me fix that.

**Comment by jfrolich** [comment]
Ok so I've been working on this, and it revealed some issues with the current approach that don't translate well to tagged template literals. So the fix is a bit more entailing than I thought.

The solution will be be a breaking change, so that's a good catch before we release 1.0.

The previous approach was to call the `name` function on a fragment, to get the fragment's name. So if you had a fragment like this: 

```reason
[%graphql {|
  query UserQuery {
    user {
      ...Avatar_User
    }
  }
|}]
```

It would call `Avatar_User.name` to get the actual name of the fragment. What I'd like to do is keep the spread static (not getting the name using a function call), because this dynamism is not allowed in the `gql` template tag as it cannot optimize the query. We just now have to make sure `Avatar_User` is also the name of the fragment. We can enforce this in the typesystem by calling a function in the parse function that expects a certain return type unique for the name (like a polymorphic variant).

I also like to make spreading submodules like `Fragments.Document` not allowed anymore. You have to alias it to 

```reason
module Document  = Fragments.Document
```

The reason for this is that dots are not allowed in the name of the fragment spread in the GraphQL spec and it breaks graphql plugins that do things like autocomplete (because it becomes an invalid query).

Let me know any feedback on this approach!

**Comment by jfrolich** [comment]
Progress here #162. I'll also add the return type option there.

**Comment by jeddeloh** [comment]
It all sounds great to me. Requiring the Fragment to be aliased locally is still an improvement over the manual inclusion that is required in Javascript.

**Comment by jfrolich** [comment]
Should be resolved now!
