### ISSUE TITLE
template tag doesn’t work with Gatsby since beta 12

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#165]
Gatsby doesn’t seem to like this code:

```js
var query = (require("gatsby").graphql`...`)
```

It raises this error:

> Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was left in the compiled code.
> 
> Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby.

Downgrading to beta 11 fixes it. 

It seems like Gatsby is extremely strict about how its queries are written in JS, and the `require(“gatsby”).graphql` style isn’t supported by its compiler.

**Comment by jfrolich** [comment]
Just use template tag (without import) for Gatsby for now. I raised this issue with Gatsby and plan to do a PR to fix this within Gatsby. We need this in order to support multiple queries.

**Comment by jfrolich** [comment]
See issue here: https://github.com/gatsbyjs/gatsby/issues/25406

**Comment by souhe** [comment]
Unfortunately since Gatsby v3 just using template tag (without import) doesn't work. Here is the error I get:
```
Using the global `graphql` tag for Gatsby's queries isn't supported as of v3.
Import it instead like:  import { graphql } from 'gatsby'
```

@jfrolich do you have any other suggestions how can we make it works?

**Comment by jfrolich** [comment]
I think the only way is to make the `require` syntax work in the gatsby babel plugin. Unless ReScript will incorporate support for tagged template literals.

**Comment by kepi** [comment]
After more than an hour struggle with getting this working, here is snippet to get `graphql-ppx` working in ReScript + Gatsby. Hopefully it would be of some use for those newbies struggling with too many things at once as me :)

```json
  "ppx-flags": [
    [
      "@reasonml-community/graphql-ppx/ppx",
      "-template-tag=graphql"
    ]
  ]
```

```rescript
%%raw("import { graphql } from 'gatsby'")

%graphql(`
query {
...
}`)
```

If there is better way, I'll be glad to know.

Btw. @jfrolich I know this is problem which isn't caused by this ppx, but wouldn't be better to leave this issue open untill it is working?

At least in my case, I checked docs, found [reason-gatsby-starter](https://github.com/jfrolich/reason-gatsby-starter-blog/blob/master/src/pages/index.re) and tried to get it working. When it wasn't, I checked opened issues and as there were none, I has been trying to fix my code untill I dig to closed issues too :)

Btw. I'm not sure if you know that gatsbyjs/gatsby#25406 has been closed this January, probably in some maintenance. But if I understand it correctly, rescript-lang/rescript-compiler#4070 is only proper way forward anyway :/
