### ISSUE TITLE
Add docstrings to generated code better documentation in editor

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/graphql-ppx#88]

**Comment by jsiebern** [comment]
I have done a little research on this. I believe that RLS will rain on this parade currently.

Take the following test code:
```reason
/**Some Doc String*/
type some_t = {test: string};

let x = {test: ""};
let y: some_t = {test: ""};
```

I have made these observations:
- Hovering over `some_t` directly on the definition doesn't do anything
- Hovering over `x` will show the correct type, but not the comment
   <img width="566" alt="Bildschirmfoto 2020-05-10 um 01 52 45" src="https://user-images.githubusercontent.com/6476589/81487766-02856100-9261-11ea-92c8-eb4fa497e566.png">
- Hovering `some_t` on `y` will show the type **with** the comment
   <img width="593" alt="Bildschirmfoto 2020-05-10 um 01 53 57" src="https://user-images.githubusercontent.com/6476589/81487775-2052c600-9261-11ea-96bd-2091529fd395.png">
- Hovering over `y` (expecting the type constraint to maybe change something), results in the same as `x`

The current RLS behavior poses a problem, as the end goal would be to display some information about the result (after it has been processed by a client lib). Without RLS displaying comments on inferred types, it's not really worth adding them at this point. 

Sure, we could add comments to `parse` / `serialize` for example, but as these get used internally by the client libs, I don't see the point either.

I then thought about adding docs the module, so that when you hover `MyQuery` after using it somewhere it would display something useful. Also no dice, the comment again get's omitted in RLS:
<img width="593" alt="Bildschirmfoto 2020-05-10 um 02 01 40" src="https://user-images.githubusercontent.com/6476589/81487889-707e5800-9262-11ea-83c5-a5eadd7c3c3f.png">

Please let me know if I misinterpreted the idea / intention for this issue.
